### ISSUE TITLE
Sensor Calibration

### ISSUE THREAD

**Issue by EBUJOLD** [xinabox/SW01#1]
Hi,

We were writing code and testing the SW01 sensor and we found that the temperatures were reporting very high on all of our xChips. 
We were reading temperatures around 79-82 degrees F in a 68-71 degree room. 

**Troubleshooting attempted:**

* We tested the same code on 4 different SW01 xChips. 
* This issue occurs on our codes and on the example codes. 
* We read the libraries and found no glaring issues
* We read the datasheet and found no glaring issues

Thank you for your time

**Comment by nickcounts** [comment]
Attached is a comparison plot of our temperature sensor and Bjarke's. Ours is indoors (our office) and I presume his is as well.

Neither of these data look reasonable to us at first glance. Any ideas?

<img width="400" alt="screen shot 2017-06-21 at 3 59 40 pm" src="https://user-images.githubusercontent.com/10506020/27404459-264a084c-569c-11e7-9ff3-26ac34043204.png">

**Comment by brendanvanbreda** [comment]
@EBUJOLD  Thanx for feedback will look into it.

**Comment by nickcounts** [comment]
I went over the data a little more today and realized the sawtooth I posted from Bjarke is some kind of artifact from bad filtering on my part. His data looks smooth (and reasonable)

<img width="400" alt="screen shot 2017-06-22 at 9 13 17 am" src="https://user-images.githubusercontent.com/10506020/27435796-2f563cf0-572b-11e7-812c-9edf9a0c323a.png">
